name: Test and build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
env:
  TEST_IMAGE_REF: netvisor-api-client-tester:${{ github.sha }}

jobs:
  test:
    name: Run tox tests & lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Tester Docker image
        run: docker build . --file tests.dockerfile --tag ${{ env.TEST_IMAGE_REF }}
      - name: Run tests
        run: docker run --rm ${{ env.TEST_IMAGE_REF }}
